

---EXERCÍCIO 1 - TRAZER TODOS OS FUNCIONÁRIOS LISTANDO NOME, DATA DE NASCIMENTO E A DESCRIÇÃO DO CARGO

SELECT
FUNC.NM_FUNCIONARIO,
FUNC.DT_NASCIMENTO,
CARGO.DS_CARGO
FROM
DB_FUNCIONARIO FUNC  JOIN DB_CARGO CARGO ON FUNC.CD_CARGO = CARGO.CD_CARGO 
WHERE 
CARGO.DS_CARGO IS NULL
ORDER BY NM_FUNCIONARIO


SELECT
FUNC.NM_FUNCIONARIO,
FUNC.DT_NASCIMENTO,
CARGO.DS_CARGO
FROM
DB_FUNCIONARIO FUNC,
DB_CARGO CARGO 
WHERE FUNC.CD_CARGO = CARGO.CD_CARGO 
ORDER BY NM_FUNCIONARIO

--EXERCÍCIO 2 - SELECIONAR TODOS OS CLIENTES PESSOA FÍSICA, LISTANDO CÓDIGO, NOME, CPF E ENDEREÇO COMPLETO

SELECT 
           DB_CLIENTE.NR_CLIENTE,
           DB_CLIENTE.NM_CLIENTE,
           DB_CLI_FISICA.NR_CPF,
           DB_LOGRADOURO.NM_LOGRADOURO,
           DB_END_CLI.NR_END,
           DB_END_CLI.DS_COMPLEMENTO_END,
           DB_LOGRADOURO.NR_CEP,
           DB_BAIRRO.NM_BAIRRO,
           DB_CIDADE.NM_CIDADE,
           DB_CIDADE.SG_ESTADO           
FROM

           DB_CLIENTE
JOIN       DB_CLI_FISICA     ON DB_CLIENTE.NR_CLIENTE        = DB_CLI_FISICA.NR_CLIENTE
LEFT JOIN  DB_END_CLI        ON DB_CLIENTE.NR_CLIENTE        = DB_END_CLI.NR_CLIENTE
LEFT JOIN  DB_LOGRADOURO     ON DB_END_CLI.CD_LOGRADOURO_CLI = DB_LOGRADOURO.CD_LOGRADOURO
LEFT JOIN  DB_BAIRRO         ON DB_BAIRRO.CD_BAIRRO          = DB_LOGRADOURO.CD_BAIRRO
LEFT JOIN  DB_CIDADE         ON DB_CIDADE.CD_CIDADE          = DB_BAIRRO.CD_CIDADE

SELECT COUNT(1) FROM DB_CLIENTE
SELECT COUNT(1) FROM DB_CLI_FISICA
SELECT COUNT(1) FROM DB_CLI_JURIDICA




---EXERCÍCIO 3 - SELECIONAR TODOS OS PEDIDOS REALIZADOS EM 2019, LISTANDO O NÚMERO DO PEDIDO, O NOME DO MOTOBOY,
---DESCRIÇÃO DO CARGO (DO MOTOBOY) E O NOME DO CLIENTE

SELECT 
DB_PEDIDO.NR_PEDIDO            AS "NÚMERO DO PEDIDO",
DB_PEDIDO.DT_PEDIDO            AS "DATA DO PEDIDO",
DB_FUNCIONARIO.NM_FUNCIONARIO  AS "NOME MOTOBOY",
DB_CARGO.DS_CARGO              AS "CARGO",
DB_CLIENTE.NM_CLIENTE          AS "NM_CLIENTE"
FROM
           DB_PEDIDO 
LEFT  JOIN DB_FUNCIONARIO ON DB_PEDIDO.CD_FUNC_MOTOBOY = DB_FUNCIONARIO.CD_FUNCIONARIO
LEFT  JOIN DB_CARGO       ON DB_FUNCIONARIO.CD_CARGO   = DB_CARGO.CD_CARGO
LEFT  JOIN DB_CLIENTE     ON DB_PEDIDO.NR_CLIENTE      = DB_CLIENTE.NR_CLIENTE
WHERE
--DB_PEDIDO.DT_PEDIDO BETWEEN '01/01/19' AND '31/12/19'
TO_CHAR(DT_PEDIDO, 'YYYY') = 2019
ORDER BY DT_PEDIDO DESC


/* EXERCÍCIO 4 - SELECIONAR TODOS OS PEDIDOS REALIZADOS PELA ATENDENTE JULIANA MORIBE, LISTANDO O NÚMERO DO PEDIDO, A DATA DO PEDIDO
E A DATA PREVISTA DA ENTREGA, ORDENADOS PELA DATA DO PEDIDO  */

SELECT 
DB_PEDIDO.NR_PEDIDO            AS "NÚMERO DO PEDIDO",
DB_PEDIDO.DT_PEDIDO            AS "DATA DO PEDIDO",
DB_FUNCIONARIO.NM_FUNCIONARIO  AS "NOME FUNCIONÁRIO",
DB_PEDIDO.DT_PREV_ENTREGA      AS "DATA PREVISTA ENTREGA"
FROM
           DB_PEDIDO 
INNER JOIN DB_FUNCIONARIO ON DB_PEDIDO.CD_FUNC_ATD = DB_FUNCIONARIO.CD_FUNCIONARIO
WHERE      
DB_FUNCIONARIO.NM_FUNCIONARIO = 'Juliana Moribe'
ORDER BY
"DATA DO PEDIDO"


--EXERCÍCIO 5 - LISTAR TODAS AS LOJAS DO ESTADO DA BAHIA, TRAZENDO: NÚMERO DA LOJA, NOME DA LOJA, NOME DA CIDADE E SIGLE DA UF

SELECT   
           DB_LOJA.NR_LOJA,
           DB_LOJA.NM_LOJA,
           DB_CIDADE.NM_CIDADE,
           DB_CIDADE.SG_ESTADO           
FROM

           DB_LOJA
JOIN       DB_END_LOJA       ON DB_END_LOJA.NR_LOJA          = DB_LOJA.NR_LOJA
JOIN       DB_LOGRADOURO     ON DB_END_LOJA.CD_LOGRADOURO    = DB_LOGRADOURO.CD_LOGRADOURO
JOIN       DB_BAIRRO         ON DB_BAIRRO.CD_BAIRRO          = DB_LOGRADOURO.CD_BAIRRO
JOIN       DB_CIDADE         ON DB_CIDADE.CD_CIDADE          = DB_BAIRRO.CD_CIDADE
WHERE      DB_CIDADE.SG_ESTADO = 'BA'

---EXERCÍCIO 6 - LISTAR TODOS OS FUNCIONÁRIOS COM CARGO DE "CHAPEIRO". TRAZER O NOME DO FUNCIONÁRIO, DATA DE CADASTRO, NOME DO DEPARTAMENTO E CARGO 

SELECT
FUNC.NM_FUNCIONARIO,
FUNC.DT_CADASTRAMENTO,
DEPTO.NM_DEPTO,
CARGO.DS_CARGO
FROM
     DB_FUNCIONARIO FUNC  
JOIN DB_CARGO CARGO ON FUNC.CD_CARGO  = CARGO.CD_CARGO 
JOIN DB_DEPTO DEPTO ON DEPTO.CD_DEPTO = CARGO.CD_DEPTO
WHERE 
CARGO.DS_CARGO = 'Chapeiro'
ORDER BY NM_FUNCIONARIO



WHERE DB_FUNCIONARIO.CD_FUNCIONARIO IS NULL


















